-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
from MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') LIKE '%-03-%' and TLNO is not NULL and GENDER = 'W'
order by MEMBER_ID asc